---
- import_tasks: install_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
- import_tasks: install_linux.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install tmux.conf
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    follow: false
    force: true

- name: Install tmux plugin manager
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: ~/.tmux/plugins/tpm
    depth: 1
    version: "HEAD"
