---
- import_tasks: install_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"

- import_tasks: install_linux.yml
  when: ansible_facts['os_family'] == "Debian"

- name: create nvim config directory
  file:
    path: ~/.config/nvim
    state: directory
    mode: "0700"

- name: symlink config files
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
    state: link
    follow: false
    force: true
